"""
================================================================================
EPOCH TRADING SYSTEM - MODULE 12: INDICATOR ANALYSIS
Calculation: Options Win Rate by Model (CALC-O01)
XIII Trading LLC
================================================================================

PURPOSE:
    Calculate win/loss statistics for OPTIONS trades by trading model (EPCH01-04).
    Uses stop-based outcomes from CALC-O09 (Options Stop Analysis).

    Win = 1R target reached before stop hit
    Loss = Stop hit before reaching 1R target

    Default stop: 25% (stop_25pct)

DATA SOURCE:
    This module uses stop analysis outcomes from CALC-O09.
    The outcomes are generated by op_stop_analysis module using op_mfe_mae_potential data.

USAGE:
    from calculations.options.op_win_rate_by_model import (
        calculate_options_win_rate_by_model,
        calculate_options_win_rate_by_model_contract,
        render_options_model_summary_table,
        render_options_model_win_loss_chart,
        render_options_model_breakdown
    )

    # Get stop outcomes from selector
    stop_outcomes = get_selected_op_stop_outcomes()

    # Calculate statistics
    model_stats = calculate_options_win_rate_by_model(stop_outcomes)

    # Display in Streamlit
    render_options_model_breakdown(stop_outcomes, stop_name="25%")

================================================================================
"""

# =============================================================================
# IMPORTS
# =============================================================================
import pandas as pd
from typing import List, Dict, Any
import streamlit as st
import plotly.graph_objects as go


# =============================================================================
# CONFIGURATION
# =============================================================================
MODELS = ["EPCH01", "EPCH02", "EPCH03", "EPCH04"]

CHART_COLORS = {
    "win": "#26a69a",
    "loss": "#ef5350",
    "background": "#1a1a2e",
    "paper": "#16213e",
    "text": "#e0e0e0"
}


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================
def _normalize_model(model_name: str) -> str:
    """Convert EPCH1 -> EPCH01, EPCH2 -> EPCH02, etc."""
    if model_name is None:
        return None
    if model_name in MODELS:
        return model_name
    model_map = {
        "EPCH1": "EPCH01", "EPCH2": "EPCH02",
        "EPCH3": "EPCH03", "EPCH4": "EPCH04"
    }
    return model_map.get(model_name, model_name)


# =============================================================================
# MAIN CALCULATION FUNCTION
# =============================================================================
def calculate_options_win_rate_by_model(
    stop_outcomes: List[Dict[str, Any]]
) -> pd.DataFrame:
    """
    Calculate win/loss statistics by model using stop-based outcomes.

    Win = outcome == 'WIN' (1R target reached before stop hit)
    Loss = outcome == 'LOSS' (stop hit before reaching 1R)

    Parameters:
    -----------
    stop_outcomes : List[Dict[str, Any]]
        List of outcome records from stop analysis.
        Each record contains:
        - trade_id: Unique trade identifier
        - model: EPCH01-04
        - contract_type: CALL or PUT
        - outcome: 'WIN' or 'LOSS'
        - r_achieved: R multiple achieved
        - stop_type: Stop type used (e.g., "stop_25pct")

    Returns:
    --------
    pd.DataFrame
        DataFrame with columns: Model, Wins, Losses, Win%, Avg R, Total
        Rows are ordered: EPCH01, EPCH02, EPCH03, EPCH04
    """
    if not stop_outcomes:
        return pd.DataFrame(columns=["Model", "Wins", "Losses", "Win%", "Avg R", "Total"])

    df = pd.DataFrame(stop_outcomes)

    if "model" not in df.columns or "outcome" not in df.columns:
        return pd.DataFrame(columns=["Model", "Wins", "Losses", "Win%", "Avg R", "Total"])

    # Normalize model names
    df["model"] = df["model"].apply(_normalize_model)

    # Determine win/loss from outcome
    df["is_winner"] = df["outcome"] == 'WIN'

    # Group by model
    stats = df.groupby("model").agg(
        Wins=("is_winner", "sum"),
        Total=("is_winner", "count"),
        AvgR=("r_achieved", "mean")
    ).reset_index()

    # Calculate losses and win percentage
    stats["Losses"] = stats["Total"] - stats["Wins"]
    stats["Win%"] = stats.apply(
        lambda row: round((row["Wins"] / row["Total"]) * 100, 1) if row["Total"] > 0 else 0,
        axis=1
    )
    stats["Avg R"] = stats["AvgR"].round(2)

    # Rename and reorder
    stats = stats.rename(columns={"model": "Model"})
    stats = stats[["Model", "Wins", "Losses", "Win%", "Avg R", "Total"]]

    # Ensure all models present
    all_models = pd.DataFrame({"Model": MODELS})
    result = all_models.merge(stats, on="Model", how="left")
    result = result.fillna(0)
    result["Wins"] = result["Wins"].astype(int)
    result["Losses"] = result["Losses"].astype(int)
    result["Total"] = result["Total"].astype(int)

    return result


def calculate_options_win_rate_by_model_contract(
    stop_outcomes: List[Dict[str, Any]]
) -> pd.DataFrame:
    """
    Calculate win/loss statistics by model AND contract type using stop outcomes.

    Parameters:
    -----------
    stop_outcomes : List[Dict[str, Any]]
        Outcome records from stop analysis

    Returns:
    --------
    pd.DataFrame
        DataFrame with columns: Model, Contract, Wins, Losses, Win%, Avg R
    """
    if not stop_outcomes:
        return pd.DataFrame(columns=["Model", "Contract", "Wins", "Losses", "Win%", "Avg R"])

    df = pd.DataFrame(stop_outcomes)

    required_cols = ["model", "outcome", "contract_type"]
    if not all(col in df.columns for col in required_cols):
        return pd.DataFrame(columns=["Model", "Contract", "Wins", "Losses", "Win%", "Avg R"])

    # Normalize
    df["model"] = df["model"].apply(_normalize_model)
    df["contract_type"] = df["contract_type"].str.upper()
    df["is_winner"] = df["outcome"] == 'WIN'

    results = []
    for model in MODELS:
        for contract in ["CALL", "PUT"]:
            mask = (df["model"] == model) & (df["contract_type"] == contract)
            subset = df[mask]

            if len(subset) == 0:
                continue

            wins = subset["is_winner"].sum()
            total = len(subset)
            losses = total - wins
            win_pct = round((wins / total) * 100, 1) if total > 0 else 0
            avg_r = round(subset["r_achieved"].mean(), 2)

            results.append({
                "Model": model,
                "Contract": contract,
                "Wins": int(wins),
                "Losses": int(losses),
                "Win%": win_pct,
                "Avg R": avg_r
            })

    return pd.DataFrame(results)


# =============================================================================
# STREAMLIT DISPLAY FUNCTIONS
# =============================================================================
def render_options_model_summary_table(model_stats: pd.DataFrame) -> None:
    """
    Display the options model statistics as a formatted Streamlit table.

    Parameters:
    -----------
    model_stats : pd.DataFrame
        Output from calculate_options_win_rate_by_model()
    """
    if model_stats.empty:
        st.info("No options data available for model breakdown")
        return

    # Transpose for display (models as columns)
    display_df = model_stats.set_index("Model").T

    # Format for display
    formatted_df = display_df.copy()
    for col in formatted_df.columns:
        formatted_df[col] = formatted_df[col].astype(str)

    if "Win%" in formatted_df.index:
        formatted_df.loc["Win%"] = display_df.loc["Win%"].apply(
            lambda x: f"{float(x):.1f}%"
        )

    if "Avg R" in formatted_df.index:
        formatted_df.loc["Avg R"] = display_df.loc["Avg R"].apply(
            lambda x: f"{float(x):+.2f}R"
        )

    st.dataframe(
        formatted_df.astype(str),
        use_container_width=True,
        height=250
    )


def render_options_model_win_loss_chart(model_stats: pd.DataFrame) -> None:
    """
    Display a grouped bar chart showing wins and losses per model for OPTIONS.

    Parameters:
    -----------
    model_stats : pd.DataFrame
        Output from calculate_options_win_rate_by_model()
    """
    if model_stats.empty:
        st.info("No options data available for chart")
        return

    fig = go.Figure()

    fig.add_trace(
        go.Bar(
            name="Wins",
            x=model_stats["Model"],
            y=model_stats["Wins"],
            marker_color=CHART_COLORS["win"],
            text=model_stats["Wins"],
            textposition="auto"
        )
    )

    fig.add_trace(
        go.Bar(
            name="Losses",
            x=model_stats["Model"],
            y=model_stats["Losses"],
            marker_color=CHART_COLORS["loss"],
            text=model_stats["Losses"],
            textposition="auto"
        )
    )

    fig.update_layout(
        title="Options Win/Loss Count by Model",
        barmode="group",
        paper_bgcolor=CHART_COLORS["paper"],
        plot_bgcolor=CHART_COLORS["background"],
        font=dict(color=CHART_COLORS["text"]),
        height=400,
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="right",
            x=1
        ),
        margin=dict(l=50, r=50, t=80, b=50)
    )

    fig.update_xaxes(title="Model")
    fig.update_yaxes(title="Number of Trades")

    st.plotly_chart(fig, use_container_width=True)


def render_options_model_breakdown(
    stop_outcomes: List[Dict[str, Any]],
    stop_name: str = "25%"
) -> pd.DataFrame:
    """
    Calculate and render options model breakdown using stop-based outcomes.

    Parameters:
    -----------
    stop_outcomes : List[Dict[str, Any]]
        Outcome records from stop analysis
    stop_name : str
        Display name of the stop type (e.g., "25%")

    Returns:
    --------
    pd.DataFrame
        The model statistics DataFrame (for Monte AI integration)
    """
    # Calculate stats
    model_stats = calculate_options_win_rate_by_model(stop_outcomes)

    st.subheader("Options Win Rate by Model")
    st.markdown(f"*Using {stop_name} Stop | Win = 1R target reached before stop hit*")

    if model_stats.empty:
        st.warning("No stop-based outcomes available")
        return model_stats

    # Summary row
    total_wins = model_stats["Wins"].sum()
    total_losses = model_stats["Losses"].sum()
    total_trades = model_stats["Total"].sum()
    overall_wr = (total_wins / total_trades * 100) if total_trades > 0 else 0

    # Calculate overall avg R
    if stop_outcomes:
        df = pd.DataFrame(stop_outcomes)
        overall_avg_r = df["r_achieved"].mean() if "r_achieved" in df.columns else 0
    else:
        overall_avg_r = 0

    # Summary cards
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Total Trades", f"{total_trades:,}")
    with col2:
        st.metric("Wins", f"{total_wins:,}")
    with col3:
        st.metric("Losses", f"{total_losses:,}")
    with col4:
        st.metric("Overall Win Rate", f"{overall_wr:.1f}%")

    st.markdown("---")

    # Two columns: table and chart
    col1, col2 = st.columns([1, 1])

    with col1:
        st.markdown("**Summary by Model**")
        render_options_model_summary_table(model_stats)

    with col2:
        st.markdown("**Win/Loss Distribution**")
        render_options_model_win_loss_chart(model_stats)

    st.markdown("---")

    # By contract type
    st.markdown("**By Model and Contract Type**")
    contract_stats = calculate_options_win_rate_by_model_contract(stop_outcomes)
    if not contract_stats.empty:
        # Format for display
        display_contract = contract_stats.copy()
        display_contract["Win%"] = display_contract["Win%"].apply(lambda x: f"{x:.1f}%")
        display_contract["Avg R"] = display_contract["Avg R"].apply(lambda x: f"{x:+.2f}R")
        st.dataframe(display_contract, use_container_width=True, hide_index=True)
    else:
        st.info("No contract type data available")

    return model_stats


# =============================================================================
# EXAMPLE USAGE (for testing)
# =============================================================================
if __name__ == "__main__":
    # Sample stop outcomes (simulating what comes from stop analysis)
    sample_outcomes = [
        {"model": "EPCH01", "outcome": "WIN", "r_achieved": 1.0, "contract_type": "CALL"},
        {"model": "EPCH01", "outcome": "LOSS", "r_achieved": -1.0, "contract_type": "CALL"},
        {"model": "EPCH01", "outcome": "WIN", "r_achieved": 1.0, "contract_type": "PUT"},
        {"model": "EPCH02", "outcome": "LOSS", "r_achieved": -1.0, "contract_type": "CALL"},
        {"model": "EPCH02", "outcome": "WIN", "r_achieved": 1.0, "contract_type": "CALL"},
        {"model": "EPCH02", "outcome": "LOSS", "r_achieved": -0.5, "contract_type": "PUT"},
        {"model": "EPCH03", "outcome": "WIN", "r_achieved": 0.8, "contract_type": "CALL"},
        {"model": "EPCH04", "outcome": "LOSS", "r_achieved": -1.0, "contract_type": "PUT"},
    ]

    result = calculate_options_win_rate_by_model(sample_outcomes)
    print("\nOptions Win Rate Statistics by Model (Stop-Based):")
    print("=" * 50)
    print(result.to_string(index=False))

    contract_result = calculate_options_win_rate_by_model_contract(sample_outcomes)
    print("\n\nOptions Win Rate Statistics by Model + Contract:")
    print("=" * 50)
    print(contract_result.to_string(index=False))
